
brands = {
    "apple": ["iphone", "macbook", "ipad"],
    "microsoft": ["windows", "teams", "xbox"],
    "amazon": ["echo", "kindle", "amazon prime"],
    "google": ["gmail", "chrome"],
    "samsung": ["galaxy s"],
    "toyota": ["camry", "corolla"],
    "mercedes-benz": ["glc-class", "amg", "mercedes"],
    "coca-cola": ["be less white", "coke", "cocacola", "coca cola"],
    "nike": ["air max", "air jordan", "dri-fit", "just do it"],
    "bmw": ["Rolls-Royce", "x5", "m3"],
    "mcdonald's": ["big mac", "mcnuggets", "happy meal", "mcdonalds", "mcflurries"],
    "tesla": ["model s", "cyber truck", "model x"],
    "disney": ["mickey mouse", "encanto", "doorables"],
    "louis vuitton": ["speedy bag", "neverfull tote", "keepall bag"],
    "cisco": ["catalyst switches", "webex", "meraki"],
    "instagram": ["reels", "igtv"],
    "adobe": ["photoshop", "acrobat", "premiere pro"],
    "ibm": ["spss", "watson"],
    "oracle": ["java"],
    "sap": ["s/4hana", "successfactors", "ariba"],
    "facebook": ["messenger"],
    "chanel": ["no. 5", "boy bag", "classic flap"],
    "hermes": ["birkin"],
    "intel": ["core i7", "xeon", "pentium"],
    "youtube": [],
    "j.p. morgan": ["jp morgan"],
    "honda": ["civic", "cr-v"],
    "american express": ["platinum card", "amex"],
    "ikea": ["tempelhof", "poäng chair", "kallax"],
    "accenture": [],
    "allianz": [],
    "hyundai": ["elantra"],
    "ups": [],
    "gucci": ["gg marmont", "princetown loafers", "dionysus bag"],
    "pepsi": [],
    "sony": ["playstation", "bravia", "xperia"],
    "visa": [],
    "salesforce": [],
    "netflix": [],
    "paypal": ["zettle", "venmo", "braintree"],
    "mastercard": [],
    "adidas": ["ultraboost", "nmd", "superstar"],
    "zara": ["red temptation"],
    "axa": [],
    "audi": ["q5", "q7", "a8"],
    "airbnb": [],
    "porsche": ["taycan", "cayenne", "panamera"],
    "starbucks": ["frappuccino"],
    "ge": ["general electric"],
    "volkswagen": ["passat", "jetta", "tiguan"],
    "ford": ["mach e", "mach-e", "bronco", "f150"],
    "nescafé": ["dolce gusto"],
    "siemens": ["healthineers"],
    "goldman sachs": ["goldmansachs"],
    "pampers": ["swaddlers"],
    "h&m": ["conscious collection", "h and m", "hem"],
    "l’oréal paris": [
        "metal detox",
        "wonder water",
        "dream lengths",
        "loreal",
        "l'oreal",
    ],
    "citi": ["citigroup", "citibank"],
    "lego": ["piece 26047", "piece 32557", "piece 11031", "legos"],
    "red bull": [],
    "budweiser": ["bud light"],
    "ebay": [],
    "nissan": ["altima", "sentra", "pathfinder"],
    "hp": ["reverb g2", "envy 6055", "victus"],
    "hsbc": ["citizens bank", "zelle"],
    "morgan stanley": ["shareworks", "morganstanley"],
    "nestle": ["kitkat", "maggi", "toll house"],
    "philips": ["3200 lattego", "sonicare", "avent"],
    "spotify": [],
    "ferrari": ["488 gtb", "sf90", "daytona sp3", "purosangue"],
    "nintendo": ["switch lite", "switch oled", "switch games", "zelda", "mario"],
    "gillette": ["king c", "exfoliating razor"],
    "colgate": ["hum toothbrush", "optic white", "overnight pen"],
    "cartier": ["tank watch", "juste un clou", "tank must"],
    "3m": ["mmm"],
    "dior": ["sauvage", "dossier"],
    "santander": [],
    "danone": ["activia", "evian", "oikos", "danon"],
    "kellogg's": ["frosted flakes", "special k", "kelloggs","kellogg", "kellogs"],
    "linkedin": ["linked in"],
    "corona": [],
    "fedex": [],
    "caterpillar": ["cat 229d3", "cat 259d3", "cat engine"],
    "dhl": [],
    "jack daniel's": [
        "old no. 7",
        "jack honey",
        "tennessee honey",
        "jack daniels",
        "jack whiskey",
    ],
    "prada": ["paradoxe", "cleo bag", "cloudbust"],
    "xiaomi": ["mi 11", "redmi", "mi band"],
    "kia": ["sorento", "sportage", "telluride"],
    "tiffany & co.": ["tiffany co", "tiffany and co"],
    "panasonic": ["lumix", "toughbook", "s5 ii"],
    "hewlett packard enterprise": [
        "proliant",
        "nimble storage",
        "hewlett hackard",
        "hpe",
    ],
    "huawei": ["mate 60", "p30", "matebook"],
    "hennessy": ["pink whitney", "casamigos"],
    "burberry": ["goddess perfume", "her elixir", "her london dream"],
    "kfc": ["kentucky fried", "zinger", "kentucky chicken"],
    "johnson & johnson": ["jnj", "johnson johnson", "johnson and johnson", "johnson 8 johnson"],
    "sephora": [],
    "nespresso": ["vertuoline", "originalline", "vertuo"],
    "heineken": [],
    "canon": ["ts3322", "pixma", "ts3522"],
}

brands_dict = {
    "apple": [],
    "microsoft": [],
    "amazon": [],
    "google": [],
    "samsung": [],
    "toyota": [],
    "mercedes-benz": [],
    "coca-cola": [],
    "nike": [],
    "bmw": [],
    "mcdonald's": [],
    "tesla": [],
    "disney": [],
    "louis vuitton": [],
    "cisco": [],
    "instagram": [],
    "adobe": [],
    "ibm": [],
    "oracle": [],
    "sap": [],
    "facebook": [],
    "chanel": [],
    "hermes": [],
    "intel": [],
    "youtube": [],
    "j.p. morgan": [],
    "honda": [],
    "american express": [],
    "ikea": [],
    "accenture": [],
    "allianz": [],
    "hyundai": [],
    "ups": [],
    "gucci": [],
    "pepsi": [],
    "sony": [],
    "visa": [],
    "salesforce": [],
    "netflix": [],
    "paypal": [],
    "mastercard": [],
    "adidas": [],
    "zara": [],
    "axa": [],
    "audi": [],
    "airbnb": [],
    "porsche": [],
    "starbucks": [],
    "ge": [],
    "volkswagen": [],
    "ford": [],
    "nescafé": [],
    "siemens": [],
    "goldman sachs": [],
    "pampers": [],
    "h&m": [],
    "l’oréal paris": [],
    "citi": [],
    "lego": [],
    "red bull": [],
    "budweiser": [],
    "ebay": [],
    "nissan": [],
    "hp": [],
    "hsbc": [],
    "morgan stanley": [],
    "nestle": [],
    "philips": [],
    "spotify": [],
    "ferrari": [],
    "nintendo": [],
    "gillette": [],
    "colgate": [],
    "cartier": [],
    "3m": [],
    "dior": [],
    "santander": [],
    "danone": [],
    "kellogg's": [],
    "linkedin": [],
    "corona": [],
    "fedex": [],
    "caterpillar": [],
    "dhl": [],
    "jack daniel's": [],
    "prada": [],
    "xiaomi": [],
    "kia": [],
    "tiffany & co.": [],
    "panasonic": [],
    "hewlett packard enterprise": [],
    "huawei": [],
    "hennessy": [],
    "burberry": [],
    "kfc": [],
    "johnson & johnson": [],
    "sephora": [],
    "nespresso": [],
    "heineken": [],
    "canon": []
}
